@startuml
actor User
participant "System" as sys

User -> sys: searchBooks(query)
activate sys

sys -> sys: search catalog by title, author or isbn
sys -> sys: filter results

sys --> User: List of found books
deactivate sys
@enduml