@startuml
Package "Models" {
class Book {
  - title: String
  - author: String
  - publicationYear: int
  - ISBN: String
  - availableCopies: int
  + editDetails()
  + isAvailable(): boolean
}

class Member {
  - name: String
  - age: int
  - memberId: String
  - email: String
}

class Librarian {
  - employeeId: String
  + addBook(book: Book)
  + removeBook(book: Book)
  + editMember(member: Member)
  }
}

Package Service {
class Loan {
  - loanDate: Date
  - dueDate: Date
  - returnDate: Date
  + markReturned()
  + isOverdue(): boolean
   }
class MemberService {
  + borrowBook(book: Book)
  + returnBook(book: Book)
   }
class BookService {
  + borrowBook(book: Book)
  + returnBook(book: Book)
  }
}

Package Repository {
class LibrarySystem {
  - books: List<Book>
  - members: List<Member>
  - loans: List<Loan>
  + searchBooks(query: String)
  + addMember(member: Member)
  + trackLoan(loan: Loan)
  }
}

LibrarySystem --> Book : manages >
LibrarySystem --> Member : manages >
LibrarySystem --> Loan : tracks >
Loan --> Book : relates to >
Loan --> Member : borrowed by >
Librarian --> LibrarySystem : uses >
@enduml