@startuml
Package "Models" {
class Book {
  - title: String
  - author: String
  - publicationYear: int
  - ISBN: String
  - availableCopies: int
  // getter, setter, equals, hashcode
  }
class Member {
  - name: String
  - age: int
  - memberId: String
  - email: String
  // getter, setter, equals, hashcode
  }
class Loan {
  - loanID String
  - loanDate: Date
  - dueDate: Date
  - returnDate: Date
  // getter, setter, equals, hashcode
  }
}

Package "Service" {

class MemberService {
 - MemberRepository members
  }
class BookService {
 - BookRepository books

  }
class LoanService {
 - LoanRepository loans
  }
}

Package "Repository" {
class LoanRepository {
  - loans: List<Loan>
  + markReturned()
  + isOverdue(): boolean
  + borrowBook(book: Book)
  + returnBook(book: Book)
  + searchBooks(query: String)
  + trackLoan(loan: Loan)
  }
class BookRepository {
  - books: List<Book>
  + editDetails()
  + isAvailable(): boolean
  + addNewBook(book: Book)
  + removeBook(book: Book)
  }
class MemberRepository {
  - members: List<Member>
  + addMember(member: Member)
  + editMember(member: Member)


  }
}

class LibrarySystemMain {

}

BookService --> BookRepository : implements
MemberService --> MemberRepository : implements
LoanService --> LoanRepository : implements
BookRepository --> Book : manages >
MemberRepository --> Member : manages >
LoanRepository --> Loan : manages >
LoanService <-- BookService : relates to >
LoanService <-- MemberService : borrowed by <



@enduml