@startuml
'https://plantuml.com/use-case-diagram

"Library member" as member
Librarian as librarian

(Search book on title, author, ISBN) as (search)
(Manage books: Add, edit, remove book) as (manage book)
(Manage members: add, edit, remove member) as (manage member)
(Borrow book) as (borrow)
(Update available copies in library) as (update)

member -> (search)
librarian --> (search)
librarian --> (manage book)
librarian --> (manage member)
member --> borrow

@enduml